//Buzzer Tocando Pirulito Que Bate Bate
//Projeto Robótica - Profs. Iuri e Rudinei

int som = 9;
int Do = 262;
int Re = 294;
int Mi = 330;
int Fa = 349;
int Sol = 392;
int La = 440;
int Si = 494;
int Do1 = 277;
int Re1 = 311;
int Fa1 = 370;
int Sol1 = 415;
int La1 = 466;
int Do2 = 523;
int Re2 = 587;
int Mi2 = 659;

void setup () {
pinMode (som, OUTPUT);
tone (som, Mi);
delay (200);
noTone (som);
tone (som, Fa);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
tone (som, Fa);
delay (200);
noTone (som);
tone (som, Mi);
delay (200);
noTone (som);
tone (som, La);
delay (200);
noTone (som);
tone (som, La);
delay (200);
noTone (som);
delay (200);
tone (som, Re);
delay (200);
noTone (som);
tone (som, Mi);
delay (200);
noTone (som);
tone (som, Fa);
delay (200);
noTone (som);
tone (som, Fa);
delay (200);
noTone (som);
tone (som, Fa);
delay (200);
noTone (som);
tone (som, Mi);
delay (200);
noTone (som);
tone (som, Re);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
delay (200);
tone (som, Mi);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
tone (som, Fa);
delay (200);
noTone (som);
tone (som, Mi);
delay (200);
noTone (som);
tone (som, Do2);
delay (200);
noTone (som);
tone (som, Si);
delay (200);
noTone (som);
tone (som, La);
delay (200);
noTone (som);
tone (som, Sol);
delay (200);
noTone (som);
tone (som, Fa);
delay (200);
noTone (som);
tone (som, Mi);
delay (200);
noTone (som);
tone (som, Re);
delay (200);
noTone (som);
tone (som, Do);
delay (200);
noTone (som);
}

void loop () {
}
